- worlds/MetroCUBEvania/progression.txt
There is a yaml option that requires you to have all 5 medals to goal: starting medal, lava medal, ice medal, cage medal, and springboards medal. There are no checks behind the gate that requires all medals, so they are all macguffins. The counterfeit medal is a logically irrelevant filler item.
> MetroCUBEvania: Fix very incorrect medal classifications

- worlds/Stardew Valley/progression.txt
Every item needs to be crafted or cooked when the corresponding  option is enabled, which is impossible without the recipes. They were falsely marked as useful or filler, presumably by people who play without these options enabled.
> Correctly assign progression to Craftsanity and Cooksanity recipes

- worlds/Stardew Valley/progression.txt
Progressive Trash Can locks the Trash Can upgrade checks at Clint's.
> fix Trash Can logic

- worlds/Aquaria/progression.txt
This fully reworks Aquaria. It has all variations of all items from AP0.5.1, AP0.6.0, AQ1.5.1 and AQ1.5.2. I think. Please let no one ever edit this god awful file again lmao.
It's intended that there is a duplicate of most names with capitalisation differences. It's intended that there are differences in progression / useful status of some items as they have changed classification since then.
If any item gets added after this, it can probably be considered BAD_NAME unless explicitly proven otherwise.
> Fully rework Aquaria

- worlds/Terraria/progression.txt
Changes to somethings that were marked incorrectly. Changes were done to non-Calamity Terraria stuff. Some Post-<event flag> stuff was marked as filler or useful, but should be marked as progression and vice versa. Reward stuff was changed in sense that if something would help with a check it was marked as useful, as all rewards are obtainable regularly in game, and if not marked as filler. No matter what "Reward: Star Cloak" is incorrectly marked as a trap.
> Some Vanilla Terraria mark changes

- worlds/Psychonauts/progression.txt
Campers' Brains changed to McGuffins (only progression is letting you goal in Brain Hunt), all other items now match current logic.
> Update Psychonauts progression.txt

- worlds/Aquaria/progression.txt
The bot has added a few new capitalization versions of item names since Palex did his major cleanup.  This sets the classification of the new names to the same thing as the other capitalization version.
I also reclassified Sun Key as filler as the developer will be reclassifying this in the apworld.
https://discord.com/channels/731205301247803413/1257452465272389687/1355231947713941564
> Aquaria - Classified new duplicate items and reclassified Sun Key

- worlds/The Legend of Zelda - Oracle of Ages/progression.txt
Master Keys will effectively be having all of the small (and boss, depending on setting) keys, so the classification should match those.  The master key option has not been implemented yet, which is why nobody has encountered these to classify them yet.
> OoA - Classify Master Keys as progression

- worlds/Adventure/progression.txt
The default classification for Right Difficulty Switch is filler, but depending on settings, its classification can be progression.  Specifically, if dragon_slay_check is true and difficulty_switch_b is option_hard_with_unlock_item, then it's progression.
https://github.com/ArchipelagoMW/Archipelago/blob/193faa00ce1d22209e7552643f968356a16ec139/worlds/adventure/__init__.py#L161
> Adventure - Make Right Difficulty Switch Progression

- worlds/Super Mario World/progression.txt
Boss Token is definitely a mcguffin; it is only needed to goal.  The Princess is a "Victory" item on the goal location that is unobtainable without releasing/sending it.
> SMW - Reclassify mcguffins

- worlds/Super Mario 64/progression.txt
1up Mushroom is classified as filler in the apworld. https://github.com/ArchipelagoMW/Archipelago/blob/193faa00ce1d22209e7552643f968356a16ec139/worlds/sm64ex/Items.py#L22
> SM64 - Reclassify 1Up Mushroom as filler

- worlds/Final Fantasy/progression.txt
I reclassified Shard and the Orbs as mcguffins, because they are required for goal but not for any multiworld checks (the chests in the final dungeon are never multiworld locations).  On the standard goal, you need all four orbs to fight the final boss.  On the shard hunt goal, you need some amount of shards to fight the final boss.  This change doesn't even matter for orbs, because they're always local items, not multiworld items.  Shards can be multiworld items.
> Final Fantasy - Reclassify mcguffins

- worlds/Mario Kart 64/progression.txt
Added classification for the few items that were missing it.  Also corrected classification of a few older items (items that were in older versions of the apworld but not the latest version).
> MK64 - Classify miscellaneous items

- worlds/Super Mario Land 2/progression.txt
Classified many unknown items.
Reclassified some midway bells and cancel auto scrolls to match the apworld. Reclassified some of the named coins as mcguffins (they were inconsistently classified). Added a few item names from an older version of the apworld since most of the names from that apworld were already in the list.
There are a few ambiguous items in the list for Auto Scroll and Cancel Auto Scroll.  I believe there are typos in the apworld code causing it to generate items that were intended to be skipped, and possibly not generate items that it intended to include.  The code is still clear on which Cancel Auto Scrolls are supposed to be useful, so I followed that intention.  I think the Auto Scroll and Cancel Auto Scroll for Mario's Castle were intended to not exist, so they don't …
> SML2 - Updated the whole list

- worlds/EarthBound/progression.txt
I went through the entire list and updated the classifications to match the apworld.  There is definitely a lot of gray area in how useful something must be to be considered useful, so it makes since that users would have classified things inconsistently.
The only two oddballs in the list are ATM Card and Sound Stone, since you start with both of them; they're not in the multiworld.  I called the ATM Card progression and Sound Stone mcguffin because if the apworld ever changed so that you didn't start with them, that's what I'd expect them to be.  (ATM Card progression for shopsanity checks; Sound Stone unlocking no checks, just goal)
> Earthbound - Update all classifications

- worlds/Donkey Kong Country 3/progression.txt
Banana Bird is definitely a mcguffin; they unlock no checks but are needed to goal if the goal is Banana Bird Hunt (15 by default).
Bonus Coins are needed to unlock levels (with checks) in the last world (15/level by default), and all of those levels need to be unlocked in order to goal if the goal is Knautilus.
Krematoa Cogs are only needed to reach Knautilus for that goal; 5 are needed.
DK Coins are used to get the Gyrocopter, which is progression and not needed for goal.  However, you need 10-41 of them to unlock it (30 by default).  That seems like it matches this bot's definition of a mcguffin.
Donkey Kong is not used at all.  It's just the "Victory" item on the goal location.
Progressive Boat Upgrade is the only non-mcguffin progression for DKC3.  All the other "progression" items …
> DKC3 - Reclassify mcguffins

- worlds/Undertale/progression.txt
The Mystery Key, featured in Undertale's beta apworld, is used to access the house directly to the right of Napstablook's house. Each of the 6 diary entries inside the locked house is a location. This means you need the Mystery Key to reach a few locations. That means its classification has to be progression.
> Change Mystery Key classification to progression

- worlds/The Minish Cap/progression.txt
20 and 50 Rupees can be considered as filler. 100 and 200 Rupees can keep useful as there are checks behind pay wall, and you get enough of the 100 Rupees to buy them.
> The Minish Cap Change Rupees classification

- worlds/SMZ3/progression.txt
- worlds/Super Metroid/progression.txt
Energy Tanks, Missiles, Power Bombs, Reserve Tanks, and Super Missiles are not important enough by themselves to be categorized/treated as full Progression items. This PR marks them as McGuffins so that AP Alert bot users won't be constantly and unnecessarily notified about receiving additional ammo/health capacity.
> Super Metroid/SMZ3 McGuffins

- worlds/Jak and Daxter_ The Precursor Legacy/progression.txt
Bunch of mislabeled stuff. There is also an extra folder for this game? I think because the colon in the title was added when the game became officially supported!
> Update Jak and Daxter's progression.txt
